### ISSUE TITLE
hackUMBC logo covering sign-up page

### ISSUE THREAD

**Issue by TheB0SS37** [umbchackers/hackumbc-web#28]
<img width="1329" alt="image" src="https://github.com/user-attachments/assets/b49356ca-49c1-4aa7-9e4b-1c5c7b9358c1">

The logo is covering the first name. Tested on desktop Firefox. Recommend removing or centering to top / making smaller.

**Comment by darshp623** [comment]
this might only be on firefox so idk someone else has to fix this

**Comment by darshp623** [comment]
interesting. still if you see anything else lmk! thanks for the feedback
